# Generated by Django 2.0.1 on 2018-10-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
