# Generated by Django 2.0.5 on 2018-10-07 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_auto_20181006_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='like',
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='student_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('ONE', 'I'), ('TWO', 'II'), ('THREE', 'III'), ('FOUR', 'IV'), ('FIVE', 'V'), ('SIX', 'VI'), ('SEVEN', 'VII'), ('EIGHT', 'VIII')], max_length=100),
        ),
    ]
