# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-07 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20181007_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='bmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSpent', models.IntegerField(default=0)),
                ('height', models.DecimalField(decimal_places=4, default=0.0, help_text='Please enter your height', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, help_text='Please enter your weight', max_digits=10)),
                ('BMI', models.DecimalField(decimal_places=4, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
